version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=lev
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db